POST http://localhost:3333/events
Content-Type: application/json

{
    "name": "Conferência de Tecnologia 2026",
    "description": "Palestras sobre últimas tendências",
    "date": "2026-06-15 09:00:00",
    "location": "Centro de Convenções - São Paulo",
    "maxAttendees": 500
}
###

GET http://localhost:3333/events
# GET http://localhost:3333/events?search=Conferência

###

PUT http://localhost:3333/events/{EVENT_ID}
Content-Type: application/json

{
    "name": "Conferência Atualizada",
    "description": "Descrição atualizada",
    "date": "2026-07-20 10:00:00",
    "location": "Centro de Convenções - Rio de Janeiro",
    "maxAttendees": 600
}

###

DELETE http://localhost:3333/events/5c8c6f3a-4b37-4d37-a972-a82f43c35b6e

###

POST http://localhost:3333/events/{EVENT_ID}/register

###

DELETE http://localhost:3333/events/{EVENT_ID}/register


